dataset_params:
  im_path: 'ucf-images'
  video_path: 'data/UCF101'
  video_ext: 'avi'
  num_images_train : 8
  frame_height: 256
  frame_width: 256
  frame_channels: 3
  num_frames: 16
  frame_interval: 3
  centre_square_crop : True
  video_filter_path: 'dataset/ucf_filter.txt'
  ae_frame_sample_prob : 0.1

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

ditv_params:
  patch_size : 2
  num_layers : 12
  hidden_size : 768
  num_heads : 12
  head_dim : 64
  timestep_emb_dim : 256

autoencoder_params:
  z_channels: 4
  codebook_size : 8192
  down_channels : [128, 256, 384, 512]
  mid_channels : [512]
  down_sample : [True, True, True]
  attn_down : [False, False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2


train_params:
  seed : 1111
  task_name: 'ucf'
  autoencoder_batch_size: 4
  autoencoder_epochs: 30
  autoencoder_lr: 0.00001
  autoencoder_acc_steps: 1
  disc_start: 5000
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 1
  kl_weight: 0.000005
  autoencoder_img_save_steps: 64
  save_latents: False
  ditv_batch_size: 4
  ditv_epochs: 1000
  num_samples: 1
  ditv_lr: 0.0001
  ditv_acc_steps: 1
  save_video_latent_dir: 'video_latents'
  vae_latent_dir_name: 'vae_latents'
  ditv_ckpt_name: 'dit_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
